### ISSUE TITLE
A quick question on how exactly to configure links

### ISSUE THREAD

**Issue by cappuccinocosmico** [teenrock/discord-chan-link#1]
In the readme.md file, it shows how to install the bot, and I have it working until that point. I am just a little confused on how to configure the links between the servers. Is there a place in a config file to put them? Or am I just missing out on some documentation?

Anyway if you get around to responding thanks for helping me out!

**Comment by teenrock** [comment]
You only need to change BOT_TOKEN in "./config.json" , bring it to life with node DLB.js and then add it to each server wich you want to link between.
Each configuration files will be automatically genereted during this step.
If you don't want to give administrator access to your bot, you should know that minimal rights he needs is manage channels (to let it create the new linked channel on servJoin) , needs manage webhook and manage messages, read message.

Sorry for the reaction time
